
/**
 *
 * @author valez
 */
public class Eliminar_registro extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Eliminar_registro.class.getName());

    /**
     * Creates new form Eliminar_registro
     */
    public Eliminar_registro() {
        initComponents();
        
        this.setSize(300, 300);           // 1. Define el ancho y alto
        this.setLocationRelativeTo(null); // 2. Centra la ventana en la pantalla
        this.setResizable(false);         // 3. Evita que la estiren o deformen
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        texto_dni = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("ELIMINAR REGISTRO");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 160, 30));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("DNI de paciente:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 20));

        jButton2.setText("REGRESAR");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        texto_dni.addActionListener(this::texto_dniActionPerformed);
        getContentPane().add(texto_dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 90, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // 1. Capturar el DNI que escribiste en la caja de texto
    String dniBuscado = texto_dni.getText().trim();
    java.util.List<String> listaLineas = new java.util.ArrayList<>();
    
    try {
        // 2. Leer el archivo línea por línea
        java.io.File archivo = new java.io.File("registros.txt");
        java.util.Scanner lector = new java.util.Scanner(archivo);
        
        while (lector.hasNextLine()) {
            String linea = lector.nextLine();
            String[] datos = linea.split(",");
            
            // 3. Si el DNI coincide (está en la posición 2), se omite (se borra)
            if (datos.length >= 8 && datos[2].equals(dniBuscado)) {
                continue; // Salta esta línea para que no se guarde
            }
            
            // Las demás líneas se conservan
            listaLineas.add(linea);
        }
        lector.close();
        
        // 4. Sobrescribir el archivo de texto limpio sin el registro eliminado
        java.io.PrintWriter escritor = new java.io.PrintWriter("registros.txt");
        for (String l : listaLineas) {
            escritor.println(l);
        }
        escritor.close();
        
        javax.swing.JOptionPane.showMessageDialog(this, "¡Registro eliminado con éxito!");
        
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al eliminar: " + e.getMessage());
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void texto_dniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto_dniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texto_dniActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Eliminar_registro().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField texto_dni;
    // End of variables declaration//GEN-END:variables
}
