
/**
 *
 * @author valez
 */
public class Modificacion_receta extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Modificacion_receta.class.getName());

    /**
     * Creates new form Modificacion_receta
     */
    public Modificacion_receta() {
        initComponents();
        
        this.setSize(700, 350);           // 1. Define el ancho y alto
        this.setLocationRelativeTo(null); // 2. Centra la ventana en la pantalla
        this.setResizable(false);         // 3. Evita que la estiren o deformen
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        texto_dni = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        texto_dni1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lista_medicamento2 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        texto_dosis = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        texto_dosis1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("DNI de paciente:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 20));

        texto_dni.addActionListener(this::texto_dniActionPerformed);
        getContentPane().add(texto_dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 90, 30));

        jButton2.setText("BUSCAR");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Dosis:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 140, 190, -1));

        texto_dni1.addActionListener(this::texto_dni1ActionPerformed);
        getContentPane().add(texto_dni1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 90, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("DNI:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 50, -1));

        lista_medicamento2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Paracetamol", "Omeprazol", "Amoxicilina", "Ibuprofeno", "Carbonato de calcio" }));
        lista_medicamento2.addActionListener(this::lista_medicamento2ActionPerformed);
        getContentPane().add(lista_medicamento2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 96, 150, 30));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Cantidad:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 190, -1));
        getContentPane().add(texto_dosis, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 180, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Medicamento:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 190, -1));
        getContentPane().add(texto_dosis1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 180, -1));

        jButton3.setText("GUARDAR CAMBIOS");
        jButton3.addActionListener(this::jButton3ActionPerformed);
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 150, 40));

        jButton1.setText("REGRESAR");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void texto_dniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto_dniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texto_dniActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Captura el DNI escrito en la caja de búsqueda
    String dni = texto_dni.getText().trim();
    boolean existeReceta = false;

    try {
        // Busca directamente en recetas.txt si ya existe una receta para este DNI
        java.io.File archivoRec = new java.io.File("recetas.txt");
        if (archivoRec.exists()) {
            java.util.Scanner lectorRec = new java.util.Scanner(archivoRec.toPath());
            while (lectorRec.hasNextLine()) {
                String linea = lectorRec.nextLine();
                String[] datos = linea.split(",");
                if (datos.length >= 6 && datos[2].equals(dni)) {
                    // Rellena los campos automáticamente con los datos encontrados en la receta
                    texto_dni.setText(datos[2]);
                    lista_medicamento2.setSelectedItem(datos[3]); // O el nombre de tu combo de medicamento
                    texto_dosis1.setText(datos[4]);              // Dosis
                    texto_dosis.setText(datos[5]);               // Cantidad
                    existeReceta = true;
                    break;
                }
            }
            lectorRec.close();
        }

        if (existeReceta) {
            javax.swing.JOptionPane.showMessageDialog(this, "¡Receta encontrada y cargada para modificar!");
        } else {
            // Si no está en recetas, revisa al menos que exista en registros.txt
            boolean existeReg = false;
            java.io.File archivoReg = new java.io.File("registros.txt");
            if (archivoReg.exists()) {
                java.util.Scanner lectorReg = new java.util.Scanner(archivoReg.toPath());
                while (lectorReg.hasNextLine()) {
                    String[] datos = lectorReg.nextLine().split(",");
                    if (datos.length >= 8 && datos[2].equals(dni)) {
                        existeReg = true;
                        break;
                    }
                }
                lectorReg.close();
            }

            if (existeReg) {
                javax.swing.JOptionPane.showMessageDialog(this, "Paciente encontrado en registros pero sin receta previa. Ingresa sus datos.");
                texto_dni.setText(dni);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "El DNI no se encuentra registrado en el sistema.");
            }
        }

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al buscar: " + e.getMessage());
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void texto_dni1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto_dni1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texto_dni1ActionPerformed

    private void lista_medicamento2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lista_medicamento2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lista_medicamento2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String dni = texto_dni.getText().trim();
    String medicamento = lista_medicamento2.getSelectedItem().toString(); // Obtiene el medicamento seleccionado
    String dosis = texto_dosis1.getText().trim();                       // Obtiene el texto de la dosis
    String cantidad = texto_dosis.getText().trim();                     // Obtiene el texto de la cantidad

    try {
        // Busca el nombre y apellido actualizados del paciente en los registros
        String nombre = "", apellido = "";
        java.util.Scanner sc = new java.util.Scanner(new java.io.File("registros.txt"));
        while (sc.hasNextLine()) {
            String[] d = sc.nextLine().split(",");
            if (d.length >= 8 && d[2].equals(dni)) {
                nombre = d[0];
                apellido = d[1];
                break;
            }
        }
        sc.close();

        // Lee todas las recetas y desecha la anterior de este DNI para eliminarla
        java.util.List<String> lista = new java.util.ArrayList<>();
        java.io.File archivo = new java.io.File("recetas.txt");
        
        if (archivo.exists()) {
            java.util.Scanner sc2 = new java.util.Scanner(archivo);
            while (sc2.hasNextLine()) {
                String lin = sc2.nextLine();
                String[] d = lin.split(",");
                if (d.length >= 6 && d[2].equals(dni)) {
                    continue; // Salta la receta vieja para borrarla
                }
                lista.add(lin);
            }
            sc2.close();
        }

        // Añade la nueva receta actualizada a la lista
        lista.add(nombre + "," + apellido + "," + dni + "," + medicamento + "," + dosis + "," + cantidad);

        // Sobrescribe el archivo recetas.txt con la información actualizada
        java.io.PrintWriter pw = new java.io.PrintWriter("recetas.txt");
        for (String l : lista) {
            pw.println(l);
        }
        pw.close();

        javax.swing.JOptionPane.showMessageDialog(this, "¡Receta actualizada con éxito!");

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Modificacion_receta().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<String> lista_medicamento2;
    private javax.swing.JTextField texto_dni;
    private javax.swing.JTextField texto_dni1;
    private javax.swing.JTextField texto_dosis;
    private javax.swing.JTextField texto_dosis1;
    // End of variables declaration//GEN-END:variables
}
