
/**
 *
 * @author valez
 */
public class Modificacion_registro extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Modificacion_registro.class.getName());

    /**
     * Creates new form Modificacion_registro
     */
    public Modificacion_registro() {
        initComponents();
        
        this.setSize(900, 500);           // 1. Define el ancho y alto
        this.setLocationRelativeTo(null); // 2. Centra la ventana en la pantalla
        this.setResizable(false);         // 3. Evita que la estiren o deformen
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        texto_dni = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        texto_nombre = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        texto_apellido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        texto_dni1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        texto_caso = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        lista_especialidad = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        lista_medico = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        calendario = new com.toedter.calendar.JDateChooser();
        calendario1 = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        texto_pago = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("REGRESAR");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, -1, -1));

        texto_dni.addActionListener(this::texto_dniActionPerformed);
        getContentPane().add(texto_dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 90, 30));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("DNI de paciente:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 20));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Nombres:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 110, -1));

        texto_nombre.addActionListener(this::texto_nombreActionPerformed);
        getContentPane().add(texto_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 210, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Apellidos:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, -1, -1));

        texto_apellido.addActionListener(this::texto_apellidoActionPerformed);
        getContentPane().add(texto_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 220, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("DNI:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 50, -1));

        texto_dni1.addActionListener(this::texto_dni1ActionPerformed);
        getContentPane().add(texto_dni1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 90, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Caso:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 70, -1));

        texto_caso.addActionListener(this::texto_casoActionPerformed);
        getContentPane().add(texto_caso, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 130, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Especialidad:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 160, -1, -1));

        lista_especialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Medicina general", "Odontologia", "Enfermeria", "Nutrición", "Obstetricia", "Psicología" }));
        getContentPane().add(lista_especialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Médico:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        lista_medico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Jesus Gonzales Mendoza", "Sebastian Quispe Zuñiga", "Alonso Castillo Mamani", "Patricia Torres Sillva", "Carman Flores Vega" }));
        lista_medico.addActionListener(this::lista_medicoActionPerformed);
        getContentPane().add(lista_medico, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Fecha:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, -1, -1));

        calendario.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(calendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 140, -1));

        calendario1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(calendario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 140, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Pago:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 230, -1, -1));

        texto_pago.setText("S/.");
        texto_pago.addActionListener(this::texto_pagoActionPerformed);
        getContentPane().add(texto_pago, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 230, 80, -1));

        jButton2.setText("BUSCAR");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        jButton3.setText("GUARDAR CAMBIOS");
        jButton3.addActionListener(this::jButton3ActionPerformed);
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 290, 150, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void texto_dniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto_dniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texto_dniActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void texto_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texto_nombreActionPerformed

    private void texto_apellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto_apellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texto_apellidoActionPerformed

    private void texto_dni1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto_dni1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texto_dni1ActionPerformed

    private void texto_casoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto_casoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texto_casoActionPerformed

    private void lista_medicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lista_medicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lista_medicoActionPerformed

    private void texto_pagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto_pagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texto_pagoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //BUSCAR DNI
        String dniBuscado = texto_dni.getText().trim();
    
    try {
        java.io.File archivo = new java.io.File("registros.txt");
        java.util.Scanner lector = new java.util.Scanner(archivo);
        
        boolean encontrado = false;
        
        // Recorrer el archivo línea por línea
        while (lector.hasNextLine()) {
            String linea = lector.nextLine();
            String[] datos = linea.split(",");
            
            // Si el DNI coincide (está en la posición 2)
            if (datos.length >= 8 && datos[2].equals(dniBuscado)) {
                texto_nombre.setText(datos[0]);
                texto_apellido.setText(datos[1]);
                texto_dni.setText(datos[2]);
                texto_caso.setText(datos[3]);
                //PARA CALENDARIO
                try {
                    java.util.Date fechaParsed = new java.text.SimpleDateFormat("dd/MM/yyyy").parse(datos[6]);
                    calendario.setDate(fechaParsed);
                } catch (Exception ex) {}
                
                lista_especialidad.setSelectedItem(datos[4]);
                lista_medico.setSelectedItem(datos[5]);
                texto_pago.setText(datos[7]);
                
                encontrado = true;
                javax.swing.JOptionPane.showMessageDialog(this, "¡Paciente encontrado!");
                break;
            }
        }
        lector.close();
        
        if (!encontrado) {
            javax.swing.JOptionPane.showMessageDialog(this, "No se encontró ese DNI.");
        }
        
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al buscar: " + e.getMessage());
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //GUARDA LOS CAMBIOS Y ELIMINA ANTERIOR REGISTRO
        try {
            java.io.File f = new java.io.File("registros.txt");
            java.util.List<String> lineas = java.nio.file.Files.readAllLines(f.toPath());

            for (int i = 0; i < lineas.size(); i++) {
                if (lineas.get(i).split(",")[2].equals(texto_dni.getText().trim())) {
                    String fecha = new java.text.SimpleDateFormat("dd/MM/yyyy").format(calendario.getDate());
                    String pagoOriginal = lineas.get(i).split(",")[7];

                    lineas.set(i, texto_nombre.getText() + "," + texto_apellido.getText() + "," + texto_dni.getText() + ","
                            + texto_caso.getText() + "," + lista_especialidad.getSelectedItem() + ","
                            + lista_medico.getSelectedItem() + "," + fecha + "," + pagoOriginal);
                    break;
                }
            }
            java.nio.file.Files.write(f.toPath(), lineas);
            javax.swing.JOptionPane.showMessageDialog(this, "¡Modificado con éxito!");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Modificacion_registro().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser calendario;
    private com.toedter.calendar.JDateChooser calendario1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> lista_especialidad;
    private javax.swing.JComboBox<String> lista_medico;
    private javax.swing.JTextField texto_apellido;
    private javax.swing.JTextField texto_caso;
    private javax.swing.JTextField texto_dni;
    private javax.swing.JTextField texto_dni1;
    private javax.swing.JTextField texto_nombre;
    private javax.swing.JTextField texto_pago;
    // End of variables declaration//GEN-END:variables
}
