
/**
 *
 * @author valez
 */
public class Recetas_ extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Recetas_.class.getName());

    /**
     * Creates new form Recetas_
     */
    public Recetas_() {
        initComponents();
        
        this.setSize(1000, 700);           
        this.setLocationRelativeTo(null); 
        this.setResizable(false); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        texto_dni2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jToggleButton2 = new javax.swing.JToggleButton();
        lista_medicamento2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        texto_dosis = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        texto_cantidad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Lucida Fax", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Emisión de Recetas(Diagnóstico)");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1000, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("DNI:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jToggleButton1.setBackground(new java.awt.Color(102, 102, 102));
        jToggleButton1.setText("Modificar ");
        jToggleButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton1.addActionListener(this::jToggleButton1ActionPerformed);
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 200, 30));
        getContentPane().add(texto_dni2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 80, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Medicamento:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, -1, -1));

        jToggleButton2.setBackground(new java.awt.Color(102, 102, 102));
        jToggleButton2.setText("Agregar Receta");
        jToggleButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton2.addActionListener(this::jToggleButton2ActionPerformed);
        getContentPane().add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 200, 30));

        lista_medicamento2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Paracetamol", "Omeprazol", "Amoxicilina", "Ibuprofeno", "Carbonato de calcio" }));
        lista_medicamento2.addActionListener(this::lista_medicamento2ActionPerformed);
        getContentPane().add(lista_medicamento2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 150, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Dosis:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, -1, -1));
        getContentPane().add(texto_dosis, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, 180, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Cantidad:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 90, -1, -1));
        getContentPane().add(texto_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 90, 80, -1));

        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 970, 130));

        jScrollPane1.setBackground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTable1.setBackground(new java.awt.Color(153, 153, 153));
        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N°", "Nombres", "Apellidos", "DNI", "Medicamento", "Dosis", "Cantidad"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 970, 400));

        jMenuBar1.setBackground(new java.awt.Color(51, 51, 51));
        jMenuBar1.setForeground(new java.awt.Color(51, 51, 51));

        jMenu2.setBackground(new java.awt.Color(51, 51, 51));
        jMenu2.setForeground(new java.awt.Color(51, 51, 51));
        jMenu2.setText("Registro de Citas");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu1.setBackground(new java.awt.Color(51, 51, 51));
        jMenu1.setForeground(new java.awt.Color(51, 51, 51));
        jMenu1.setText("Reportes");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu3.setText("Recetas");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lista_medicamento2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lista_medicamento2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lista_medicamento2ActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        this.setVisible(false);
        Registro_Citas b = new Registro_Citas();
        b.setVisible(true);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        this.setVisible(false);
        Reportes_ a = new Reportes_();
        a.setVisible(true);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        try {
        String dniBuscado = texto_dni2.getText().trim();
        String medicamento = lista_medicamento2.getSelectedItem().toString();
        String dosis = texto_dosis.getText().trim();
        String cantidad = texto_cantidad.getText().trim();
        
        String nombres = "";
        String apellidos = "";
        boolean pacienteEncontrado = false;
        
        // Buscar nombres y apellidos en registros.txt usando el DNI
        java.io.File archivoRegistros = new java.io.File("registros.txt");
        if (archivoRegistros.exists()) {
            java.util.Scanner lector = new java.util.Scanner(archivoRegistros);
            while (lector.hasNextLine()) {
                String linea = lector.nextLine();
                String[] datos = linea.split(",");
                if (datos.length >= 8 && datos[2].equals(dniBuscado)) {
                    nombres = datos[0];
                    apellidos = datos[1];
                    pacienteEncontrado = true;
                    break;
                }
            }
            lector.close();
        }
        
        if (!pacienteEncontrado) {
            javax.swing.JOptionPane.showMessageDialog(this, "¡Error! No existe un paciente registrado con ese DNI.");
            return;
        }
        
        // Guardar la receta en recetas.txt
        String nuevaReceta = nombres + "," + apellidos + "," + dniBuscado + "," + medicamento + "," + dosis + "," + cantidad;
        try (java.io.FileWriter fw = new java.io.FileWriter("recetas.txt", true);
             java.io.BufferedWriter bw = new java.io.BufferedWriter(fw);
             java.io.PrintWriter out = new java.io.PrintWriter(bw)) {
            out.println(nuevaReceta);
        }
        
        // Agregar los datos ordenados exactamente como corresponden a tus columnas:
        // Columna 0: N°, Columna 1: Nombres, Columna 2: Apellidos, Columna 3: DNI, Columna 4: Medicamento, Columna 5: Dosis, Columna 6: Cantidad
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        int numeroFila = modelo.getRowCount() + 1;
        modelo.addRow(new Object[]{numeroFila, nombres, apellidos, dniBuscado, medicamento, dosis, cantidad});
        
        javax.swing.JOptionPane.showMessageDialog(this, "¡Receta agregada y guardada con éxito!");
        
        // Limpiar cajas de texto
        texto_dosis.setText("");
        texto_cantidad.setText("");
        texto_dni2.setText("");
        
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al agregar la receta: " + e.getMessage());
    }
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        this.setVisible(false);
        Modificacion_receta h = new Modificacion_receta();
        h.setVisible(true);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Recetas_().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JComboBox<String> lista_medicamento2;
    private javax.swing.JTextField texto_cantidad;
    private javax.swing.JTextField texto_dni2;
    private javax.swing.JTextField texto_dosis;
    // End of variables declaration//GEN-END:variables
}
