
/**
 *
 * @author valez
 */
public class Registro_Citas extends javax.swing.JFrame {
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Registro_Citas.class.getName());

    /**
     * Creates new form Registro_Citas
     */
    public Registro_Citas() {
        initComponents();
        
        
        
        this.setSize(1000, 600);           
        this.setLocationRelativeTo(null); 
        this.setResizable(false);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        texto_nombre = new javax.swing.JTextField();
        texto_apellido = new javax.swing.JTextField();
        texto_dni = new javax.swing.JTextField();
        texto_caso = new javax.swing.JTextField();
        lista_especialidad = new javax.swing.JComboBox<>();
        lista_medico = new javax.swing.JComboBox<>();
        calendario = new com.toedter.calendar.JDateChooser();
        texto_pago = new javax.swing.JTextField();
        boton_añadir = new javax.swing.JToggleButton();
        boton_modificar = new javax.swing.JToggleButton();
        boton_eliminar = new javax.swing.JToggleButton();
        jLabel12 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Lucida Fax", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Registro General de Citas");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1000, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Nombres:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 110, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("DNI:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 50, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Médico:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Caso:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 70, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Fecha:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Apellidos:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, -1, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Especialidad:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Pago:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 230, -1, -1));

        texto_nombre.addActionListener(this::texto_nombreActionPerformed);
        getContentPane().add(texto_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 290, -1));

        texto_apellido.addActionListener(this::texto_apellidoActionPerformed);
        getContentPane().add(texto_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, 290, -1));

        texto_dni.addActionListener(this::texto_dniActionPerformed);
        getContentPane().add(texto_dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 90, -1));

        texto_caso.addActionListener(this::texto_casoActionPerformed);
        getContentPane().add(texto_caso, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 130, -1));

        lista_especialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Medicina general", "Odontologia", "Enfermeria", "Nutrición", "Obstetricia", "Psicología" }));
        getContentPane().add(lista_especialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 160, -1, -1));

        lista_medico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Jesus Gonzales Mendoza", "Sebastian Quispe Zuñiga", "Alonso Castillo Mamani", "Patricia Torres Sillva", "Carman Flores Vega" }));
        lista_medico.addActionListener(this::lista_medicoActionPerformed);
        getContentPane().add(lista_medico, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, -1));

        calendario.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(calendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 140, -1));

        texto_pago.setText("S/.");
        texto_pago.addActionListener(this::texto_pagoActionPerformed);
        getContentPane().add(texto_pago, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 230, 80, -1));

        boton_añadir.setBackground(new java.awt.Color(102, 102, 102));
        boton_añadir.setText("Añadir");
        boton_añadir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boton_añadir.addActionListener(this::boton_añadirActionPerformed);
        getContentPane().add(boton_añadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 130, 40));

        boton_modificar.setBackground(new java.awt.Color(102, 102, 102));
        boton_modificar.setText("Modificar");
        boton_modificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boton_modificar.addActionListener(this::boton_modificarActionPerformed);
        getContentPane().add(boton_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 130, 40));

        boton_eliminar.setBackground(new java.awt.Color(102, 102, 102));
        boton_eliminar.setText("Eliminar");
        boton_eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boton_eliminar.addActionListener(this::boton_eliminarActionPerformed);
        getContentPane().add(boton_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 330, 130, 40));

        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 960, 310));

        jMenuBar1.setBackground(new java.awt.Color(51, 51, 51));
        jMenuBar1.setForeground(new java.awt.Color(51, 51, 51));

        jMenu2.setBackground(new java.awt.Color(51, 51, 51));
        jMenu2.setForeground(new java.awt.Color(51, 51, 51));
        jMenu2.setText("Registro de Citas");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu1.setBackground(new java.awt.Color(51, 51, 51));
        jMenu1.setForeground(new java.awt.Color(51, 51, 51));
        jMenu1.setText("Reportes");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu3.setText("Recetas");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void texto_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texto_nombreActionPerformed

    private void texto_apellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto_apellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texto_apellidoActionPerformed

    private void texto_dniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto_dniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texto_dniActionPerformed

    private void texto_casoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto_casoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texto_casoActionPerformed

    private void lista_medicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lista_medicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lista_medicoActionPerformed

    private void texto_pagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto_pagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texto_pagoActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        this.setVisible(false);
        Reportes_ d = new Reportes_();
        d.setVisible(true);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        this.setVisible(false);
        Recetas_ e = new Recetas_();
        e.setVisible(true);
    }//GEN-LAST:event_jMenu3MouseClicked

    private void boton_añadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_añadirActionPerformed
        try {
        // 1. Obtener la fecha seleccionada del calendario y formatearla
        String fechaStr = "";
        if (calendario.getDate() != null) {
            fechaStr = new java.text.SimpleDateFormat("dd/MM/yyyy").format(calendario.getDate());
        }
        
        // 2. Construir la línea de texto uniendo todos los campos con comas (CSV)
        String nuevaLinea = texto_nombre.getText().trim() + "," +
                            texto_apellido.getText().trim() + "," +
                            texto_dni.getText().trim() + "," +
                            texto_caso.getText().trim() + "," +
                            lista_especialidad.getSelectedItem().toString() + "," +
                            lista_medico.getSelectedItem().toString() + "," +
                            fechaStr + "," +
                            texto_pago.getText().trim();
                            
        // 3. Guardar la línea al final del archivo registros.txt (usando append = true para no borrar lo anterior)
        try (java.io.FileWriter fw = new java.io.FileWriter("registros.txt", true);
             java.io.BufferedWriter bw = new java.io.BufferedWriter(fw);
             java.io.PrintWriter out = new java.io.PrintWriter(bw)) {
            out.println(nuevaLinea);
        }
        
        javax.swing.JOptionPane.showMessageDialog(this, "¡Cita añadida y guardada con éxito!");
        
        // 4. Limpiar los campos después de guardar (opcional)
        texto_nombre.setText("");
        texto_apellido.setText("");
        texto_dni.setText("");
        texto_caso.setText("");
        texto_pago.setText("");
        
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar la cita: " + e.getMessage());
    }
    }//GEN-LAST:event_boton_añadirActionPerformed

    private void boton_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_modificarActionPerformed
        // CREAS Y MUESTRAS VENTANA DE MODIFICACION
        Modificacion_registro modificar = new Modificacion_registro();
        modificar.setVisible(true);
    }//GEN-LAST:event_boton_modificarActionPerformed

    private void boton_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_eliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_eliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Registro_Citas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton boton_añadir;
    private javax.swing.JToggleButton boton_eliminar;
    private javax.swing.JToggleButton boton_modificar;
    private com.toedter.calendar.JDateChooser calendario;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JComboBox<String> lista_especialidad;
    private javax.swing.JComboBox<String> lista_medico;
    private javax.swing.JTextField texto_apellido;
    private javax.swing.JTextField texto_caso;
    private javax.swing.JTextField texto_dni;
    private javax.swing.JTextField texto_nombre;
    private javax.swing.JTextField texto_pago;
    // End of variables declaration//GEN-END:variables
}
